### ISSUE TITLE
VM's not working

### ISSUE THREAD

**Issue by jeswinroy** [CSIRT-MU/Stream4Flow#103]
![vagrant](https://user-images.githubusercontent.com/62739228/105896979-8d9bc680-603d-11eb-9dbe-4ee9b91a093e.jpg)

The VM's are not being up on my system please help

**Comment by cermmik** [comment]
This behavior may be caused by several issues and it is hard to say which on is it based on the image. At first, please check that you have Virtualbox and that you are able to boot some virtual machine (check whether a virtualization is enabled on your machine). Second, open the booting virtual host in the VirtualBox and check if there are some error logs. Third, this is some common behavior of the Vagrant in the Windows OS. Try to deploy it several times, it will typically succeed on the next attempt.

**Comment by jeswinroy** [comment]
![cmder](https://user-images.githubusercontent.com/62739228/105982328-232a6b00-60bd-11eb-8046-99cc1fc4dd12.jpg)
Once the producer file is up it is not proceding to the next machine!
What shall I do
Also the Virtual box also gets stuck after one machine is up and running

**Comment by jeswinroy** [comment]
![machineup](https://user-images.githubusercontent.com/62739228/105986427-f0837100-60c2-11eb-9060-503a484aa431.jpg)
All the machines are now up and running but the IP address assigned are not being deployed. It is the local IP address of my system which is allocated to the virtual machines from this step how do I proceed further?

**Comment by cermmik** [comment]
You can simply change used IP addresses in the configuration file [/provisioning/configuration.yml](https://github.com/CSIRT-MU/Stream4Flow/blob/master/provisioning/configuration.yml) and then start the deployment. You can also set up IP addresses manually. Just open the virtual host and set required IP address.
